name: Page Analyzer

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Validate composer.json and composer.lock
        run: composer validate

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Run Linter
        run: make lint

      - name: Setup PostgreSQL
        uses: Harmon758/postgresql-action@v1.0.0
        with:
          postgresql version: 10
          postgresql db: domains
          postgresql user: test
          postgresql password: 1

      - name: Laravel Migrate
        env:
          DB_CONNECTION: pgsql
          DB_DATABASE: domains
          DB_USER: test
          DB_PASSWORD: 1
        run: php artisan migrate --force

      - name: Run Test
        env:
          DB_CONNECTION: pgsql
          DB_PORT: 5432
          DB_DATABASE: domains
          DB_USER: test
          DB_PASSWORD: 1
        run: php artisan test
